// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"strconv"

	entadmin "github.com/malero/ent-admin"
)

// AdminRegistry binds the generated read-only readers to client.
func AdminRegistry(client *Client) entadmin.Registry {
	return entadmin.Registry{
		Entities: []entadmin.Entity{
			{
				Name:        "Book",
				Label:       "Book",
				PluralLabel: "Books",
				Route:       "books",
				ID: entadmin.Field{
					Name:      "id",
					Label:     "Id",
					Kind:      entadmin.FieldKindInt,
					Optional:  false,
					Nillable:  false,
					Immutable: false,
					Sensitive: false,
				},
				Fields: []entadmin.Field{
					{
						Name:       "title",
						Label:      "Title",
						Kind:       entadmin.FieldKindString,
						Optional:   false,
						Nillable:   false,
						Immutable:  false,
						Sensitive:  false,
						EnumValues: []string{},
					},
					{
						Name:       "author",
						Label:      "Author",
						Kind:       entadmin.FieldKindString,
						Optional:   false,
						Nillable:   false,
						Immutable:  false,
						Sensitive:  false,
						EnumValues: []string{},
					},
					{
						Name:       "published",
						Label:      "Published",
						Kind:       entadmin.FieldKindBool,
						Optional:   false,
						Nillable:   false,
						Immutable:  false,
						Sensitive:  false,
						EnumValues: []string{},
					},
				},
				Reader: &entAdminBookReader{client: client},
			},
		},
	}
}

type entAdminBookReader struct {
	client *Client
}

func (r *entAdminBookReader) List(ctx context.Context, opts entadmin.ListOptions) (entadmin.ListResult, error) {
	query := r.client.Book.Query()
	if opts.Offset > 0 {
		query = query.Offset(opts.Offset)
	}
	if opts.Limit > 0 {
		query = query.Limit(opts.Limit)
	}
	rows, err := query.All(ctx)
	if err != nil {
		return entadmin.ListResult{}, err
	}
	records := make([]entadmin.Record, 0, len(rows))
	for _, row := range rows {
		records = append(records, entAdminBookRecord(row))
	}
	return entadmin.ListResult{Records: records}, nil
}

func (r *entAdminBookReader) Get(ctx context.Context, id string) (entadmin.Record, error) {
	parsed, err := entAdminBookID(id)
	if err != nil {
		return entadmin.Record{}, err
	}
	row, err := r.client.Book.Get(ctx, parsed)
	if err != nil {
		if IsNotFound(err) {
			return entadmin.Record{}, entadmin.ErrNotFound
		}
		return entadmin.Record{}, err
	}
	return entAdminBookRecord(row), nil
}

func entAdminBookRecord(row *Book) entadmin.Record {
	return entadmin.Record{
		ID: fmt.Sprint(row.ID),
		Values: map[string]any{
			"title":     row.Title,
			"author":    row.Author,
			"published": row.Published,
		},
	}
}

func entAdminBookID(value string) (int, error) {
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return int(0), fmt.Errorf("invalid Book id %q: %w", value, err)
	}
	return int(parsed), nil
}
